<script>
    $(document).ready(function(){
        $('#price-size').hide();
        $('#buttons').show();
        $('#price-btn').click(function(){
            $('#price-size').show();
            $('#buttons').hide();
        });
    });
</script>